services:
  backend:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis_busafe
    restart: always
    ports:
      - "6379:6379"

  db:
    # Trocamos para a imagem oficial do MongoDB
    image: mongo:latest
    container_name: mongodb_busafe
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    # Opcional: Se quiser que o banco já nasça com user/pass, 
    # use MONGO_INITDB_ROOT_USERNAME e MONGO_INITDB_ROOT_PASSWORD no .env
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: