spring.application.name=busafe

spring.datasource.url=jdbc:postgresql://localhost:5439/postgres
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
server.tomcat.max-http-form-post-size=52428800

# ativa batch no Hibernate pra acelerar inserts
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=public

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB